USE [RunningDB]
GO

/****** Object:  Index [PK_TrainingPlans]    Script Date: 26-05-2025 21:46:25 ******/
ALTER TABLE [dbo].[TrainingPlan] ADD  CONSTRAINT [PK_TrainingPlans] PRIMARY KEY CLUSTERED 
(
	[TrainingPlanID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

