USE [RunningDB]
GO

/****** Object:  Index [PK_UserTrainingPlan]    Script Date: 26-05-2025 21:44:57 ******/
ALTER TABLE [dbo].[UserTrainingPlan] ADD  CONSTRAINT [PK_UserTrainingPlan] PRIMARY KEY CLUSTERED 
(
	[UserTrainingPlanID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

